# Generated by Django 5.1.1 on 2024-09-29 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ex6app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mymodel',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='mymodel',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
    ]
