# Generated by Django 5.1.1 on 2024-09-29 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ex6app', '0002_mymodel_price_mymodel_quantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity', models.IntegerField()),
                ('description', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='MyModel',
        ),
    ]
